server:
  port: 8001

spring:
  application:
    name: eureka-server

eureka:
  instance:
    hostname: localhost
    ip-address: 127.0.0.1 #将自己的IP地址注册到Eureka服务中
    instance-id: ${spring.application.name}:${server.port}

  client:
    registerWithEureka: true #是否将自己注册到Eureka服务中，本身就是无需注册
    fetchRegistry: true #是否从Eureka中获取注册信息
    serviceUrl: #Eureka客户端和Eureka服务端交互的地址
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

  server:
      enable-self-preservation: false #是否关闭自我保护
      eviction-interval-timer-in-ms: 60000 #清理间隔（单位毫秒，默认60*1000）